services:
  # сервис БД
  mysql:
    container_name: local_mysql
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # пароль для пользователя root (суперпользователь в mysql)
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"

  # сервис админки для работы с БД (веб-клиент, поднятый в докере)
  phpmyadmin:
    container_name: local_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
